services:
  - type: web
    name: my-portfolio
    env: node
    buildCommand: npm run build
    startCommand: serve -s build
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
